export const ProfileDetails = [
  {
    id: 1,
    employeeNumber: "10176369",
    employeeNumberVerification: "Correct",
    employeeNumberVerificationRemarks: "",
    employeeName: "Vikneshwaran",
    employeeNameVerification: "Correct",
    employeeNameVerificationRemarks: "",
    cadre: "PA CO",
    cadreVerification: "",
    cadreVerificationRemarks: "",
    officeStatus: "Circle Office",
    officeStatusVerification: "",
    officeStatusVerificationRemarks: "",
    parentCircle: "Tamilnadu",
    parentCircleVerification: "",
    parentCircleVerificationRemarks: "",
    parentRegion: "Circle Office",
    parentRegionVerification: "",
    parentRegionVerificationRemarks: "",
    parentDivision: "Circle Office",
    parentDivisionVerification: "",
    parentDivisionVerificationRemarks: "",
    fatherName: "Singaram",
    fatherNameVerification: "",
    fatherNameVerificationRemarks: "",
    spouseName: "Ranju",
    spouseNameVerification: "",
    spouseNameVerificationRemarks: "",
    maritalStatus: "Married",
    maritalStatusVerification: "",
    maritalStatusVerificationRemarks: "",
    dateOfBirth: "19-01-1991",
    dateOfBirthVerification: "",
    dateOfBirthVerificationRemarks: "",
    gender: "Male",
    genderVerification: "",
    genderVerificationRemarks: "",
    category: "OBC",
    categoryVerification: "",
    categoryVerificationRemarks: "",
    presentDesignation: "",
    presentDesignationVerification: "",
    presentDesignationVerificationRemarks: "",
    dccs: "23-03-2015",
    dccsVerification: "",
    dccsVerificationRemarks: "",
    dateOfJoiningThePresentCadre: "",
    dateOfJoiningThePresentCadreVerification: "",
    dateOfJoiningThePresentCadreVerificationRemarks: "",
    personWithDisability: "",
    personWithDisabilityVerification: "",
    personWithDisabilityVerificationRemarks: "",
    disabilityDetails: "",
    disabilityDetailsVerification: "",
    disabilityDetailsVerificationRemarks: "",
    workingInAPS: "",
    workingInAPSVerification: "",
    workingInAPSVerificationRemarks: "",
    presentRole: "",
    presentRoleVerification: "",
    presentRoleVerificationRemarks: "",

    profileVerificationStatus: "Pending",
  },

  {
    id: 2,
    employeeNumber: "10000001",
    employeeNumberVerification: "Correct",
    employeeNumberVerificationRemarks: "",
    employeeName: "Vinoth",
    employeeNameVerification: "Correct",
    employeeNameVerificationRemarks: "",
    cadre: "SA",
    cadreVerification: "",
    cadreVerificationRemarks: "",
    officeStatus: "Regional Office",
    officeStatusVerification: "",
    officeStatusVerificationRemarks: "",
    parentCircle: "Karnataka",
    parentCircleVerification: "",
    parentCircleVerificationRemarks: "",
    parentRegion: "Regional Office",
    parentRegionVerification: "",
    parentRegionVerificationRemarks: "",
    parentDivision: "Regional Office",
    parentDivisionVerification: "",
    parentDivisionVerificationRemarks: "",
    fatherName: "Viki",
    fatherNameVerification: "",
    fatherNameVerificationRemarks: "",
    spouseName: "Ranju",
    spouseNameVerification: "",
    spouseNameVerificationRemarks: "",
    maritalStatus: "Married",
    maritalStatusVerification: "",
    maritalStatusVerificationRemarks: "",
    dateOfBirth: "01-01-1990",
    dateOfBirthVerification: "",
    dateOfBirthVerificationRemarks: "",
    gender: "Male",
    genderVerification: "",
    genderVerificationRemarks: "",
    category: "OBC",
    categoryVerification: "",
    categoryVerificationRemarks: "",
    presentDesignation: "",
    presentDesignationVerification: "",
    presentDesignationVerificationRemarks: "",
    dccs: "23-03-2015",
    dccsVerification: "",
    dccsVerificationRemarks: "",
    dateOfJoiningThePresentCadre: "",
    dateOfJoiningThePresentCadreVerification: "",
    dateOfJoiningThePresentCadreVerificationRemarks: "",
    personWithDisability: "",
    personWithDisabilityVerification: "",
    personWithDisabilityVerificationRemarks: "",
    disabilityDetails: "",
    disabilityDetailsVerification: "",
    disabilityDetailsVerificationRemarks: "",
    workingInAPS: "",
    workingInAPSVerification: "",
    workingInAPSVerificationRemarks: "",
    presentRole: "",
    presentRoleVerification: "",
    presentRoleVerificationRemarks: "",

    profileVerificationStatus: "Verified",
  },
  {
    id: 3,
    employeeNumber: "10000003",
    employeeNumberVerification: "Correct",
    employeeNumberVerificationRemarks: "",
    employeeName: "Archana",
    employeeNameVerification: "Correct",
    employeeNameVerificationRemarks: "",
    cadre: "SA",
    cadreVerification: "",
    cadreVerificationRemarks: "",
    officeStatus: "Circle Office",
    officeStatusVerification: "",
    officeStatusVerificationRemarks: "",
    parentCircle: "Kerala",
    parentCircleVerification: "",
    parentCircleVerificationRemarks: "",
    parentRegion: "Western Region",
    parentRegionVerification: "",
    parentRegionVerificationRemarks: "",
    parentDivision: "Western Division",
    parentDivisionVerification: "",
    parentDivisionVerificationRemarks: "",
    fatherName: "Amar",
    fatherNameVerification: "",
    fatherNameVerificationRemarks: "",
    spouseName: "",
    spouseNameVerification: "",
    spouseNameVerificationRemarks: "",
    maritalStatus: "Unmarried",
    maritalStatusVerification: "",
    maritalStatusVerificationRemarks: "",
    dateOfBirth: "01-01-1990",
    dateOfBirthVerification: "",
    dateOfBirthVerificationRemarks: "",
    gender: "Female",
    genderVerification: "",
    genderVerificationRemarks: "",
    category: "OBC",
    categoryVerification: "",
    categoryVerificationRemarks: "",
    presentDesignation: "",
    presentDesignationVerification: "",
    presentDesignationVerificationRemarks: "",
    dccs: "01-03-2015",
    dccsVerification: "",
    dccsVerificationRemarks: "",
    dateOfJoiningThePresentCadre: "",
    dateOfJoiningThePresentCadreVerification: "",
    dateOfJoiningThePresentCadreVerificationRemarks: "",
    personWithDisability: "",
    personWithDisabilityVerification: "",
    personWithDisabilityVerificationRemarks: "",
    disabilityDetails: "",
    disabilityDetailsVerification: "",
    disabilityDetailsVerificationRemarks: "",
    workingInAPS: "",
    workingInAPSVerification: "",
    workingInAPSVerificationRemarks: "",
    presentRole: "",
    presentRoleVerification: "",
    presentRoleVerificationRemarks: "",

    profileVerificationStatus: "Verified",
  },

  {
    id: 4,
    employeeNumber: "10000004",
    employeeNumberVerification: "Correct",
    employeeNumberVerificationRemarks: "",
    employeeName: "Bhuvanesh",
    employeeNameVerification: "Correct",
    employeeNameVerificationRemarks: "",
    cadre: "SA",
    cadreVerification: "",
    cadreVerificationRemarks: "",
    officeStatus: "Circle Office",
    officeStatusVerification: "",
    officeStatusVerificationRemarks: "",
    parentCircle: "Karnataka",
    parentCircleVerification: "",
    parentCircleVerificationRemarks: "",
    parentRegion: "RMS Office",
    parentRegionVerification: "",
    parentRegionVerificationRemarks: "",
    parentDivision: "RMS Office",
    parentDivisionVerification: "",
    parentDivisionVerificationRemarks: "",
    fatherName: "Bala",
    fatherNameVerification: "",
    fatherNameVerificationRemarks: "",
    spouseName: "Banu",
    spouseNameVerification: "",
    spouseNameVerificationRemarks: "",
    maritalStatus: "Married",
    maritalStatusVerification: "",
    maritalStatusVerificationRemarks: "",
    dateOfBirth: "01-01-1980",
    dateOfBirthVerification: "",
    dateOfBirthVerificationRemarks: "",
    gender: "Male",
    genderVerification: "",
    genderVerificationRemarks: "",
    category: "SC",
    categoryVerification: "",
    categoryVerificationRemarks: "",
    presentDesignation: "",
    presentDesignationVerification: "",
    presentDesignationVerificationRemarks: "",
    dccs: "23-03-2015",
    dccsVerification: "",
    dccsVerificationRemarks: "",
    dateOfJoiningThePresentCadre: "",
    dateOfJoiningThePresentCadreVerification: "",
    dateOfJoiningThePresentCadreVerificationRemarks: "",
    personWithDisability: "",
    personWithDisabilityVerification: "",
    personWithDisabilityVerificationRemarks: "",
    disabilityDetails: "",
    disabilityDetailsVerification: "",
    disabilityDetailsVerificationRemarks: "",
    workingInAPS: "",
    workingInAPSVerification: "",
    workingInAPSVerificationRemarks: "",
    presentRole: "",
    presentRoleVerification: "",
    presentRoleVerificationRemarks: "",

    profileVerificationStatus: "Pending",
  },

  {
    id: 5,
    employeeNumber: "10000005",
    employeeNumberVerification: "Incorrect",
    employeeNumberVerificationRemarks: "",
    employeeName: "Chandran",
    employeeNameVerification: "Correct",
    employeeNameVerificationRemarks: "",
    cadre: "LSG",
    cadreVerification: "",
    cadreVerificationRemarks: "",
    officeStatus: "Divisonal Office",
    officeStatusVerification: "",
    officeStatusVerificationRemarks: "",
    parentCircle: "Delhi",
    parentCircleVerification: "",
    parentCircleVerificationRemarks: "",
    parentRegion: "RMS Divisional Office",
    parentRegionVerification: "",
    parentRegionVerificationRemarks: "",
    parentDivision: "RMS Divisional Office",
    parentDivisionVerification: "",
    parentDivisionVerificationRemarks: "",
    fatherName: "Bala",
    fatherNameVerification: "",
    fatherNameVerificationRemarks: "",
    spouseName: "Chamundi",
    spouseNameVerification: "",
    spouseNameVerificationRemarks: "",
    maritalStatus: "Unmarried",
    maritalStatusVerification: "",
    maritalStatusVerificationRemarks: "",
    dateOfBirth: "10-11-1989",
    dateOfBirthVerification: "",
    dateOfBirthVerificationRemarks: "",
    gender: "Male",
    genderVerification: "",
    genderVerificationRemarks: "",
    category: "SC",
    categoryVerification: "",
    categoryVerificationRemarks: "",
    presentDesignation: "",
    presentDesignationVerification: "",
    presentDesignationVerificationRemarks: "",
    dccs: "23-03-2022",
    dccsVerification: "",
    dccsVerificationRemarks: "",
    dateOfJoiningThePresentCadre: "",
    dateOfJoiningThePresentCadreVerification: "",
    dateOfJoiningThePresentCadreVerificationRemarks: "",
    personWithDisability: "",
    personWithDisabilityVerification: "",
    personWithDisabilityVerificationRemarks: "",
    disabilityDetails: "",
    disabilityDetailsVerification: "",
    disabilityDetailsVerificationRemarks: "",
    workingInAPS: "",
    workingInAPSVerification: "",
    workingInAPSVerificationRemarks: "",
    presentRole: "",
    presentRoleVerification: "",
    presentRoleVerificationRemarks: "",

    profileVerificationStatus: "Verified",
  },
];
export const TransferDetails = [
  { id:1,
    employeeNumber: "2000001",
    employeeName: "Zaheer",
    cadre: "",
    officeStatus: "",
    officeStatusNew: "",
    officeStatusNewVerification: "",
    officeStatusNewVerificationRemarks: "",
    parentCircle: "",
    parentCircleNew: "",
    parentCircleNewVerification: "",
    parentCircleNewVerificationRemarks: "",
    parentRegion: "",
    parentRegionNew: "",
    parentRegionNewVerification: "",
    parentRegionNewVerificationRemarks: "",
    parentDivision: "",
    parentDivisionNew: "",
    parentDivisionNewVerification: "",
    parentDivisionNewVerificationRemarks: "",
    presentDesignation: "",
    presentDesignationNew: "",
    presentDesignationNewVerification: "",
    presentDesignationNewVerificationRemarks: "",
    workingInAPS: "",
    workingInAPSNew: "",
    workingInAPSNewVerification: "",
    workingInAPSNewVerificationRemarks: "",
    presentRole: "",
    presentRoleNew: "",
    presentRoleNewVerification: "",
    presentRoleNewVerificationRemarks: "",

    transferVerificationStatus:"Verified",
  },
  {
    id:2,
    employeeNumber: "20000002",
    employeeName: "yusuf",
    cadre: "",
    officeStatus: "",
    officeStatusNew: "",
    officeStatusNewVerification: "",
    officeStatusNewVerificationRemarks: "",
    parentCircle: "",
    parentCircleNew: "",
    parentCircleNewVerification: "",
    parentCircleNewVerificationRemarks: "",
    parentRegion: "",
    parentRegionNew: "",
    parentRegionNewVerification: "",
    parentRegionNewVerificationRemarks: "",
    parentDivision: "",
    parentDivisionNew: "",
    parentDivisionNewVerification: "",
    parentDivisionNewVerificationRemarks: "",
    presentDesignation: "",
    presentDesignationNew: "",
    presentDesignationNewVerification: "",
    presentDesignationNewVerificationRemarks: "",
    workingInAPS: "",
    workingInAPSNew: "",
    workingInAPSNewVerification: "",
    workingInAPSNewVerificationRemarks: "",
    presentRole: "",
    presentRoleNew: "",
    presentRoleNewVerification: "",
    presentRoleNewVerificationRemarks: "",
    transferVerificationStatus:"Pending",
  },
  {
    id:3,
    employeeNumber: "Xavier",
    employeeName: "20000003",
    cadre: "",
    officeStatus: "",
    officeStatusNew: "",
    officeStatusNewVerification: "",
    officeStatusNewVerificationRemarks: "",
    parentCircle: "",
    parentCircleNew: "",
    parentCircleNewVerification: "",
    parentCircleNewVerificationRemarks: "",
    parentRegion: "",
    parentRegionNew: "",
    parentRegionNewVerification: "",
    parentRegionNewVerificationRemarks: "",
    parentDivision: "",
    parentDivisionNew: "",
    parentDivisionNewVerification: "",
    parentDivisionNewVerificationRemarks: "",
    presentDesignation: "",
    presentDesignationNew: "",
    presentDesignationNewVerification: "",
    presentDesignationNewVerificationRemarks: "",
    workingInAPS: "",
    workingInAPSNew: "",
    workingInAPSNewVerification: "",
    workingInAPSNewVerificationRemarks: "",
    presentRole: "",
    presentRoleNew: "",
    presentRoleNewVerification: "",
    presentRoleNewVerificationRemarks: "",
    transferVerificationStatus:"Pending",
  },
  {
    id:4,
    employeeNumber: "Uvaraj",
    employeeName: "20000004",
    cadre: "",
    officeStatus: "",
    officeStatusNew: "",
    officeStatusNewVerification: "",
    officeStatusNewVerificationRemarks: "",
    parentCircle: "",
    parentCircleNew: "",
    parentCircleNewVerification: "",
    parentCircleNewVerificationRemarks: "",
    parentRegion: "",
    parentRegionNew: "",
    parentRegionNewVerification: "",
    parentRegionNewVerificationRemarks: "",
    parentDivision: "",
    parentDivisionNew: "",
    parentDivisionNewVerification: "",
    parentDivisionNewVerificationRemarks: "",
    presentDesignation: "",
    presentDesignationNew: "",
    presentDesignationNewVerification: "",
    presentDesignationNewVerificationRemarks: "",
    workingInAPS: "",
    workingInAPSNew: "",
    workingInAPSNewVerification: "",
    workingInAPSNewVerificationRemarks: "",
    presentRole: "",
    presentRoleNew: "",
    presentRoleNewVerification: "",
    presentRoleNewVerificationRemarks: "",
    transferVerificationStatus:"Pending",
  },

  {
    id:5,
    employeeNumber: "20000005",
    employeeName: "Waqar",
    cadre: "",
    officeStatus: "",
    officeStatusNew: "",
    officeStatusNewVerification: "",
    officeStatusNewVerificationRemarks: "",
    parentCircle: "",
    parentCircleNew: "",
    parentCircleNewVerification: "",
    parentCircleNewVerificationRemarks: "",
    parentRegion: "",
    parentRegionNew: "",
    parentRegionNewVerification: "",
    parentRegionNewVerificationRemarks: "",
    parentDivision: "",
    parentDivisionNew: "",
    parentDivisionNewVerification: "",
    parentDivisionNewVerificationRemarks: "",
    presentDesignation: "",
    presentDesignationNew: "",
    presentDesignationNewVerification: "",
    presentDesignationNewVerificationRemarks: "",
    workingInAPS: "",
    workingInAPSNew: "",
    workingInAPSNewVerification: "",
    workingInAPSNewVerificationRemarks: "",
    presentRole: "",
    presentRoleNew: "",
    presentRoleNewVerification: "",
    presentRoleNewVerificationRemarks: "",
    transferVerificationStatus:"Verified"
  },
  {
    id:6,
    employeeNumber: "20000006",
    employeeName: "Quantam",
    cadre: "",
    officeStatus: "",
    officeStatusNew: "",
    officeStatusNewVerification: "",
    officeStatusNewVerificationRemarks: "",
    parentCircle: "",
    parentCircleNew: "",
    parentCircleNewVerification: "",
    parentCircleNewVerificationRemarks: "",
    parentRegion: "",
    parentRegionNew: "",
    parentRegionNewVerification: "",
    parentRegionNewVerificationRemarks: "",
    parentDivision: "",
    parentDivisionNew: "",
    parentDivisionNewVerification: "",
    parentDivisionNewVerificationRemarks: "",
    presentDesignation: "",
    presentDesignationNew: "",
    presentDesignationNewVerification: "",
    presentDesignationNewVerificationRemarks: "",
    workingInAPS: "",
    workingInAPSNew: "",
    workingInAPSNewVerification: "",
    workingInAPSNewVerificationRemarks: "",
    presentRole: "",
    presentRoleNew: "",
    presentRoleNewVerification: "",
    presentRoleNewVerificationRemarks: "",
    transferVerificationStatus:"Pending"
  },

  { id:7,
    employeeNumber: "20000007",
    employeeName: "Wasim",
    cadre: "",
    officeStatus: "",
    officeStatusNew: "",
    officeStatusNewVerification: "",
    officeStatusNewVerificationRemarks: "",
    parentCircle: "",
    parentCircleNew: "",
    parentCircleNewVerification: "",
    parentCircleNewVerificationRemarks: "",
    parentRegion: "",
    parentRegionNew: "",
    parentRegionNewVerification: "",
    parentRegionNewVerificationRemarks: "",
    parentDivision: "",
    parentDivisionNew: "",
    parentDivisionNewVerification: "",
    parentDivisionNewVerificationRemarks: "",
    presentDesignation: "",
    presentDesignationNew: "",
    presentDesignationNewVerification: "",
    presentDesignationNewVerificationRemarks: "",
    workingInAPS: "",
    workingInAPSNew: "",
    workingInAPSNewVerification: "",
    workingInAPSNewVerificationRemarks: "",
    presentRole: "",
    presentRoleNew: "",
    presentRoleNewVerification: "",
    presentRoleNewVerificationRemarks: "",
    transferVerificationStatus:"Verified"
  },
];

